In [2]:
import  numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [33]:
df=pd.read_csv('diabetes.csv')

In [34]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [35]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [36]:
df=df.sample(frac=1)

In [8]:
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
205   52    1   0       128   255    0        1      161      1      0.0   
99    53    1   2       130   246    1        0      173      0      0.0   
176   60    1   0       117   230    1        1      160      1      1.4   
164   38    1   2       138   175    0        1      173      0      0.0   
95    53    1   0       142   226    0        0      111      1      0.0   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
286   59    1   3       134   204    0        1      162      0      0.8   
97    52    1   0       108   233    1        1      147      0      0.1   
21    44    1   2       130   233    0        1      179      1      0.4   
117   56    1   3       120   193    0        0      162      0      1.9   
127   67    0   2       152   277    0        1      172      0      0.0   

     slope  ca  thal  target  
205      2   1     3       0  
99       2   3     2       1  
176      2   2     3       0  
164      2   4     2       1  
95       2   0     3       1  
..     ...  ..   ...     ...  
286      2   2     2       0  
97       2   3     3       1  
21       2   0     2       1  
117      1   0     3       1  
127      2   1     2       1  

[303 rows x 14 columns]

In [37]:
X=df.drop(['target'],axis=1).values
Y=df['target'].values

KeyError: "['target'] not found in axis"

In [38]:
X

array([[52.,  1.,  0., ...,  2.,  1.,  3.],
       [53.,  1.,  2., ...,  2.,  3.,  2.],
       [60.,  1.,  0., ...,  2.,  2.,  3.],
       ...,
       [44.,  1.,  2., ...,  2.,  0.,  2.],
       [56.,  1.,  3., ...,  1.,  0.,  3.],
       [67.,  0.,  2., ...,  2.,  1.,  2.]])

In [12]:
Y

array([0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,

In [39]:
 X_train, X_test,Y_train, Y_test= train_test_split(X,Y,random_state=42)

In [40]:
knn=KNeighborsClassifier()

In [41]:
knn.fit(X_train,Y_train)

KNeighborsClassifier()

In [42]:
Y_pred=knn.predict(X_test)

In [43]:
Y_pred

array([1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 1], dtype=int64)

In [44]:
accuracy_score(Y_pred, Y_test)

0.6447368421052632

In [45]:
from sklearn.preprocessing import StandardScaler

In [46]:
std=StandardScaler()
X_train_scaled=std.fit_transform(X_train)

In [47]:
X_test_scaled=std.transform(X_test)

In [48]:
knn.fit(X_train_scaled,Y_train)

KNeighborsClassifier()

In [49]:
Y_pred=knn.predict(X_test_scaled)

In [50]:
accuracy_score(Y_test,Y_pred)

0.7894736842105263